#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x306F216180425066 (jelmer@jelmer.uk)
#
Name     : pypi-dulwich
Version  : 0.20.46
Release  : 2
URL      : https://files.pythonhosted.org/packages/4c/61/85f17dd9e744e027d23bee2bbafc8438fab26c175a089b1a06b664deae21/dulwich-0.20.46.tar.gz
Source0  : https://files.pythonhosted.org/packages/4c/61/85f17dd9e744e027d23bee2bbafc8438fab26c175a089b1a06b664deae21/dulwich-0.20.46.tar.gz
Source1  : https://files.pythonhosted.org/packages/4c/61/85f17dd9e744e027d23bee2bbafc8438fab26c175a089b1a06b664deae21/dulwich-0.20.46.tar.gz.asc
Summary  : Python Git Library
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: pypi-dulwich-bin = %{version}-%{release}
Requires: pypi-dulwich-filemap = %{version}-%{release}
Requires: pypi-dulwich-lib = %{version}-%{release}
Requires: pypi-dulwich-license = %{version}-%{release}
Requires: pypi-dulwich-python = %{version}-%{release}
Requires: pypi-dulwich-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(urllib3)

%description
Openstack Swift as backend for Dulwich
======================================
Fabien Boucher <fabien.boucher@enovance.com>

%package bin
Summary: bin components for the pypi-dulwich package.
Group: Binaries
Requires: pypi-dulwich-license = %{version}-%{release}
Requires: pypi-dulwich-filemap = %{version}-%{release}

%description bin
bin components for the pypi-dulwich package.


%package filemap
Summary: filemap components for the pypi-dulwich package.
Group: Default

%description filemap
filemap components for the pypi-dulwich package.


%package lib
Summary: lib components for the pypi-dulwich package.
Group: Libraries
Requires: pypi-dulwich-license = %{version}-%{release}
Requires: pypi-dulwich-filemap = %{version}-%{release}

%description lib
lib components for the pypi-dulwich package.


%package license
Summary: license components for the pypi-dulwich package.
Group: Default

%description license
license components for the pypi-dulwich package.


%package python
Summary: python components for the pypi-dulwich package.
Group: Default
Requires: pypi-dulwich-python3 = %{version}-%{release}

%description python
python components for the pypi-dulwich package.


%package python3
Summary: python3 components for the pypi-dulwich package.
Group: Default
Requires: pypi-dulwich-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(dulwich)
Requires: pypi(urllib3)

%description python3
python3 components for the pypi-dulwich package.


%prep
%setup -q -n dulwich-0.20.46
cd %{_builddir}/dulwich-0.20.46
pushd ..
cp -a dulwich-0.20.46 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663605106
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-dulwich
cp %{_builddir}/dulwich-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pypi-dulwich/9e9b8604dc428d3f50acf86a2e36d56e008672d6
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dul-receive-pack
/usr/bin/dul-upload-pack
/usr/bin/dulwich

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-dulwich

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-dulwich/9e9b8604dc428d3f50acf86a2e36d56e008672d6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
